# Generated by Django 4.0.4 on 2022-05-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tarifa',
            new_name='tarifa_id',
        ),
    ]
