# Generated by Django 4.0.4 on 2022-05-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_tarifa_cliente_tarifa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tarifa_id',
            new_name='tarifa',
        ),
    ]
