# Generated by Django 4.0.4 on 2022-05-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
