# Generated by Django 4.0.4 on 2022-05-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_rename_cliente_vehiculo_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
